class BG21_IJA
{
	name = "[BG21] IJA";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_IJA_HQ,HQ Squad,BG21_IJA,1,Infantry,BG21_IJA_PL,CAPTAIN,BG21_IJA_Recon,PRIVATE,BG21_IJA_Recon,PRIVATE)
		GROUP3(BG21_IJA_RECON,Recon Squad,BG21_IJA,1,Infantry,BG21_IJA_SL_Recon,SERGEANT,BG21_IJA_Recon,PRIVATE,BG21_IJA_Radio,PRIVATE)
		GROUP3(BG21_IJA_ENGINEER1,Engineer Squad (Mines),BG21_IJA,1,Infantry,BG21_IJA_Engineer_Mines,PRIVATE,BG21_IJA_Engineer_Mines,PRIVATE,BG21_IJA_Engineer_Mines,PRIVATE)
		GROUP3(BG21_IJA_ENGINEER2,Engineer Squad (Explos),BG21_IJA,1,Infantry,BG21_IJA_Engineer_Explos,PRIVATE,BG21_IJA_Engineer_Explos,PRIVATE,BG21_IJA_Engineer_Explos,PRIVATE)
		GROUP3(BG21_IJA_ENGINEER3,Engineer Squad (Mixed),BG21_IJA,1,Infantry,BG21_IJA_Engineer_Mines,PRIVATE,BG21_IJA_Engineer_Mines,PRIVATE,BG21_IJA_Engineer_Explos,PRIVATE)
		GROUP3(BG21_IJA_AT,AT Squad,BG21_IJA,1,Infantry,BG21_IJA_SL,CORPORAL,BG21_IJA_AT,PRIVATE,BG21_IJA_AT_AS,PRIVATE)
		GROUP7(BG21_IJA_INF1,Infantry Squad,BG21_IJA,1,Infantry,BG21_IJA_SL,SERGEANT,BG21_IJA_TL,CORPORAL,BG21_IJA_Rifleman,PRIVATE,BG21_IJA_Rifleman,PRIVATE,BG21_IJA_Radio,PRIVATE,BG21_IJA_MG,PRIVATE,BG21_IJA_MG_AS,PRIVATE)
	};
};
