class BG21_IJA
{
	name = "[BG21] IJA";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_IJA_HQ,HQ Squad,BG21_IJA,1,BG21_IJA_PL,CAPTAIN,BG21_IJA_Recon,PRIVATE,BG21_IJA_Recon,PRIVATE)
		GROUP3(BG21_IJA_RECON,Recon Squad,BG21_IJA,1,BG21_IJA_SL_Recon,SERGEANT,BG21_IJA_Recon,PRIVATE,BG21_IJA_Radio_Recon,PRIVATE)
		GROUP3(BG21_IJA_ENGINEER1,Engineer Squad (Mines),BG21_IJA,1,BG21_IJA_Engineer_Mines,PRIVATE,BG21_IJA_Engineer_Mines,PRIVATE,BG21_IJA_Engineer_Mines,PRIVATE)
		GROUP3(BG21_IJA_ENGINEER2,Engineer Squad (Explos),BG21_IJA,1,BG21_IJA_Engineer_Explos,PRIVATE,BG21_IJA_Engineer_Explos,PRIVATE,BG21_IJA_Engineer_Explos,PRIVATE)
		GROUP3(BG21_IJA_ENGINEER3,Engineer Squad (Mixed),BG21_IJA,1,BG21_IJA_Engineer_Mines,PRIVATE,BG21_IJA_Engineer_Mines,PRIVATE,BG21_IJA_Engineer_Explos,PRIVATE)
		GROUP3(BG21_IJA_AT,AT Squad,BG21_IJA,1,BG21_IJA_SL,CORPORAL,BG21_IJA_AT,PRIVATE,BG21_IJA_AT_AS,PRIVATE)
		GROUP3(BG21_IJA_MORTAR,Mortar Team,BG21_IJA,1,BG21_IJA_Mortar_TL,CORPORAL,BG21_IJA_MORTAR,PRIVATE,BG21_IJA_Mortar_AS,PRIVATE)
		GROUP7(BG21_IJA_INF1,Infantry Squad,BG21_IJA,1,BG21_IJA_SL,SERGEANT,BG21_IJA_TL,CORPORAL,BG21_IJA_Rifleman,PRIVATE,BG21_IJA_Rifleman,PRIVATE,BG21_IJA_Radio,PRIVATE,BG21_IJA_MG,PRIVATE,BG21_IJA_MG_AS,PRIVATE)
		
		// 73rd D-Day Anniversary
		GROUP2(BG21_IJA_HQ2,HQ (2),BG21_IJA,1,BG21_IJA_PL,CAPTAIN,BG21_IJA_PL2,LIEUTENANT)
		GROUP4(BG21_IJA_Recon4,Recon (4),BG21_IJA,1,BG21_IJA_SL_Recon,CORPORAL,BG21_IJA_Radio_Recon,PRIVATE,BG21_IJA_Recon,PRIVATE,BG21_IJA_Recon,PRIVATE)
		GROUP9(BG21_IJA_LightSupport,Light Support,BG21_IJA,1,BG21_IJA_SL,SERGEANT,BG21_IJA_Radio,PRIVATE,BG21_IJA_Medic,PRIVATE,BG21_IJA_Grenadier,PRIVATE,BG21_IJA_Rifleman,PRIVATE,BG21_IJA_Rifleman,PRIVATE,BG21_IJA_MG_TL,CORPORAL,BG21_IJA_MG,PRIVATE,BG21_IJA_MG_AS,PRIVATE)
		GROUP9(BG21_IJA_HeavySupport,Heavy Support,BG21_IJA,1,BG21_IJA_SL,SERGEANT,BG21_IJA_Radio,PRIVATE,BG21_IJA_Medic,PRIVATE,BG21_IJA_Mortar_TL,CORPORAL,BG21_IJA_Mortar,PRIVATE,BG21_IJA_Mortar_AS,PRIVATE,BG21_IJA_MG_TL,CORPORAL,BG21_IJA_MG,PRIVATE,BG21_IJA_MG_AS,PRIVATE)
		
		GROUP8(BG21_IJA_RifleSquad,Rifle Squad,BG21_IJA,1,BG21_IJA_SL,SERGEANT,BG21_IJA_Radio,PRIVATE,BG21_IJA_MG,PRIVATE,BG21_IJA_MG_AS,PRIVATE,BG21_IJA_Rifleman,PRIVATE,BG21_IJA_Rifleman,PRIVATE,BG21_IJA_Rifleman,PRIVATE,BG21_IJA_TL,CORPORAL)
		GROUP7(BG21_IJA_AssaultSquad,Assault Squad,BG21_IJA,1,BG21_IJA_SL,SERGEANT,BG21_IJA_Radio,PRIVATE,BG21_IJA_Engineer_Explos,PRIVATE,BG21_IJA_Rifleman,PRIVATE,BG21_IJA_Rifleman,PRIVATE,BG21_IJA_Rifleman,PRIVATE,BG21_IJA_TL,CORPORAL)
	};
};
