class BG21_FFI
{
	name = "[BG21] French Resistance";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_FFI_HQ,HQ squad,BG21_FFI,0,BG21_FFI_PL,CAPTAIN,BG21_FFI_Recon,PRIVATE,BG21_FFI_Recon,PRIVATE)
		GROUP3(BG21_FFI_RECON,Recon squad,BG21_FFI,0,BG21_FFI_SL,SERGEANT,BG21_FFI_Recon,PRIVATE,BG21_FFI_Recon,PRIVATE)
		GROUP3(BG21_FFI_PIONIER1,Pionier squad (Mines),BG21_FFI,0,BG21_FFI_Pioneer_Mines,PRIVATE,BG21_FFI_Pioneer_Mines,PRIVATE,BG21_FFI_Pioneer_Mines,PRIVATE)
		GROUP3(BG21_FFI_PIONIER2,Pionier squad (Explos),BG21_FFI,0,BG21_FFI_Pioneer_Explos,PRIVATE,BG21_FFI_Pioneer_Explos,PRIVATE,BG21_FFI_Pioneer_Explos,PRIVATE)
		GROUP3(BG21_FFI_PIONIER3,Pionier squad (Mixed),BG21_FFI,0,BG21_FFI_Pioneer_Mines,PRIVATE,BG21_FFI_Pioneer_Mines,PRIVATE,BG21_FFI_Pioneer_Explos,PRIVATE)
		GROUP3(BG21_FFI_AT,AT Team,BG21_FFI,0,BG21_FFI_SL,CORPORAL,BG21_FFI_AT,PRIVATE,BG21_FFI_AT_AS,PRIVATE)
		GROUP3(BG21_FFI_MORTAR,Mortar Team,BG21_FFI,0,BG21_FFI_Mortar_TL,CORPORAL,BG21_FFI_MORTAR,PRIVATE,BG21_FFI_Mortar_AS,PRIVATE)
		GROUP7(BG21_FFI_INF1,Inf. squad,BG21_FFI,0,BG21_FFI_SL,SERGEANT,BG21_FFI_Rifleman,CORPORAL,BG21_FFI_Rifleman,PRIVATE,BG21_FFI_Rifleman,PRIVATE,BG21_FFI_Radio,PRIVATE,BG21_FFI_MG,PRIVATE,BG21_FFI_MG_AS,PRIVATE)
	};
};
