class BG21_US_ARMY
{
	name = "[BG21] US Army";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_US_ARMY_HQ,HQ Team,BG21_US_ARMY,2,BG21_US_ARMY_PL,CAPTAIN,BG21_US_ARMY_Recon,PRIVATE,BG21_US_ARMY_Recon,PRIVATE)
		GROUP3(BG21_US_ARMY_RECON,Recon Team,BG21_US_ARMY,2,BG21_US_ARMY_SL,SERGEANT,BG21_US_ARMY_Recon,PRIVATE,BG21_US_ARMY_Radio,PRIVATE)
		GROUP3(BG21_US_ARMY_ENGINEER1,Engineer Team (Mines),BG21_US_ARMY,2,BG21_US_ARMY_Engineer_Mines,PRIVATE,BG21_US_ARMY_Engineer_Mines,PRIVATE,BG21_US_ARMY_Engineer_Mines,PRIVATE)
		GROUP3(BG21_US_ARMY_ENGINEER2,Engineer Team (Explos),BG21_US_ARMY,2,BG21_US_ARMY_Engineer_Explos,PRIVATE,BG21_US_ARMY_Engineer_Explos,PRIVATE,BG21_US_ARMY_Engineer_Explos,PRIVATE)
		GROUP3(BG21_US_ARMY_ENGINEER3,Engineer Team (Mixed),BG21_US_ARMY,2,BG21_US_ARMY_Engineer_Mines,PRIVATE,BG21_US_ARMY_Engineer_Mines,PRIVATE,BG21_US_ARMY_Engineer_Explos,PRIVATE)
		GROUP3(BG21_US_ARMY_AT,Anti-Tank Team,BG21_US_ARMY,2,BG21_US_ARMY_SL,CORPORAL,BG21_US_ARMY_AT,PRIVATE,BG21_US_ARMY_AT_AS,PRIVATE)
		GROUP3(BG21_US_ARMY_MORTAR,Mortar Team,BG21_US_ARMY,2,BG21_US_ARMY_Mortar_TL,CORPORAL,BG21_US_ARMY_Mortar,PRIVATE,BG21_US_ARMY_Mortar_AS,PRIVATE)
		GROUP7(BG21_US_ARMY_INF1,Infantry Squad,BG21_US_ARMY,2,BG21_US_ARMY_SL,SERGEANT,BG21_US_ARMY_TL,CORPORAL,BG21_US_ARMY_Rifleman,PRIVATE,BG21_US_ARMY_Rifleman,PRIVATE,BG21_US_ARMY_Radio,PRIVATE,BG21_US_ARMY_MG,PRIVATE,BG21_US_ARMY_MG_AS,PRIVATE)
		GROUP2(BG21_US_ARMY_TANK1,Tank crew (2),BG21_US_ARMY,2,BG21_US_ARMY_Tank_Commander,SERGEANT,BG21_US_ARMY_Tank_Crew,PRIVATE)
		GROUP3(BG21_US_ARMY_TANK2,Tank crew (3),BG21_US_ARMY,2,BG21_US_ARMY_Tank_Commander,SERGEANT,BG21_US_ARMY_Tank_Crew,CORPORAL,BG21_US_ARMY_Tank_Crew,PRIVATE)
		// 73rd D-Day anniversary
		GROUP2(BG21_US_ARMY_HQ2,HQ (2),BG21_US_ARMY,2,BG21_US_ARMY_PL,CAPTAIN,BG21_US_ARMY_PL2,LIEUTENANT)
		GROUP4(BG21_US_ARMY_Recon4,Recon (4),BG21_US_ARMY,2,BG21_US_ARMY_Recon_TL,CORPORAL,BG21_US_ARMY_Recon,PRIVATE,BG21_US_ARMY_Recon,PRIVATE,BG21_US_ARMY_Recon,PRIVATE)
		GROUP9(BG21_US_ARMY_LightSupport,Light Support,BG21_US_ARMY,2,BG21_US_ARMY_SL,SERGEANT,BG21_US_ARMY_Radio,PRIVATE,BG21_US_ARMY_Medic,PRIVATE,BG21_US_ARMY_Grenadier,PRIVATE,BG21_US_ARMY_Rifleman,PRIVATE,BG21_US_ARMY_Rifleman,PRIVATE,BG21_US_ARMY_MG_TL,CORPORAL,BG21_US_ARMY_MG,PRIVATE,BG21_US_ARMY_MG_AS_TRIPOD,PRIVATE)
		GROUP9(BG21_US_ARMY_HeavySupport,Heavy Support,BG21_US_ARMY,2,BG21_US_ARMY_SL,SERGEANT,BG21_US_ARMY_Radio,PRIVATE,BG21_US_ARMY_Medic,PRIVATE,BG21_US_ARMY_Mortar_TL,CORPORAL,BG21_US_ARMY_Mortar,PRIVATE,BG21_US_ARMY_Mortar_AS,PRIVATE,BG21_US_ARMY_MG_TL,CORPORAL,BG21_US_ARMY_MG,PRIVATE,BG21_US_ARMY_MG_AS_TRIPOD,PRIVATE)
		GROUP8(BG21_US_ARMY_RifleSquad,Rifle Squad,BG21_US_ARMY,2,BG21_US_ARMY_SL,SERGEANT,BG21_US_ARMY_Radio,PRIVATE,BG21_US_ARMY_MG,PRIVATE,BG21_US_ARMY_MG_AS,PRIVATE,BG21_US_ARMY_Rifleman,PRIVATE,BG21_US_ARMY_Rifleman,PRIVATE,BG21_US_ARMY_Rifleman,PRIVATE,BG21_US_ARMY_TL,CORPORAL)
		GROUP7(BG21_US_ARMY_AssaultSquad,Assault Squad,BG21_US_ARMY,2,BG21_US_ARMY_SL,SERGEANT,BG21_US_ARMY_Radio,PRIVATE,BG21_US_ARMY_Engineer_Explos,PRIVATE,BG21_US_ARMY_Rifleman,PRIVATE,BG21_US_ARMY_BAR,PRIVATE,BG21_US_ARMY_BAR,PRIVATE,BG21_US_ARMY_TL,CORPORAL)
	};
};
class BG21_US_ARMY_W
{
	name = "[BG21] US Army (Winter)";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_US_ARMY_W_HQ,HQ Team,BG21_US_ARMY_W,2,BG21_US_ARMY_W_PL,CAPTAIN,BG21_US_ARMY_W_Recon,PRIVATE,BG21_US_ARMY_W_Recon,PRIVATE)
		GROUP3(BG21_US_ARMY_W_RECON,Recon Team,BG21_US_ARMY_W,2,BG21_US_ARMY_W_SL,SERGEANT,BG21_US_ARMY_W_Recon,PRIVATE,BG21_US_ARMY_W_Radio,PRIVATE)
		GROUP3(BG21_US_ARMY_W_ENGINEER1,Engineer Team (Mines),BG21_US_ARMY_W,2,BG21_US_ARMY_W_Engineer_Mines,PRIVATE,BG21_US_ARMY_W_Engineer_Mines,PRIVATE,BG21_US_ARMY_W_Engineer_Mines,PRIVATE)
		GROUP3(BG21_US_ARMY_W_ENGINEER2,Engineer Team (Explos),BG21_US_ARMY_W,2,BG21_US_ARMY_W_Engineer_Explos,PRIVATE,BG21_US_ARMY_W_Engineer_Explos,PRIVATE,BG21_US_ARMY_W_Engineer_Explos,PRIVATE)
		GROUP3(BG21_US_ARMY_W_ENGINEER3,Engineer Team (Mixed),BG21_US_ARMY_W,2,BG21_US_ARMY_W_Engineer_Mines,PRIVATE,BG21_US_ARMY_W_Engineer_Mines,PRIVATE,BG21_US_ARMY_W_Engineer_Explos,PRIVATE)
		GROUP3(BG21_US_ARMY_W_AT,Anti-Tank Team,BG21_US_ARMY_W,2,BG21_US_ARMY_W_SL,CORPORAL,BG21_US_ARMY_W_AT,PRIVATE,BG21_US_ARMY_W_AT_AS,PRIVATE)
		GROUP3(BG21_US_ARMY_W_MORTAR,Mortar Team,BG21_US_ARMY_W,2,BG21_US_ARMY_W_Mortar_TL,CORPORAL,BG21_US_ARMY_W_Mortar,PRIVATE,BG21_US_ARMY_W_Mortar_AS,PRIVATE)
		GROUP7(BG21_US_ARMY_W_INF1,Infantry Squad,BG21_US_ARMY_W,2,BG21_US_ARMY_W_SL,SERGEANT,BG21_US_ARMY_W_TL,CORPORAL,BG21_US_ARMY_W_Rifleman,PRIVATE,BG21_US_ARMY_W_Rifleman,PRIVATE,BG21_US_ARMY_W_Radio,PRIVATE,BG21_US_ARMY_W_MG,PRIVATE,BG21_US_ARMY_W_MG_AS,PRIVATE)
		// 73rd D-Day anniversary
		GROUP2(BG21_US_ARMY_W_HQ2,HQ (2),BG21_US_ARMY_W,2,BG21_US_ARMY_W_PL,CAPTAIN,BG21_US_ARMY_W_PL2,LIEUTENANT)
		GROUP4(BG21_US_ARMY_W_Recon4,Recon (4),BG21_US_ARMY_W,2,BG21_US_ARMY_W_Recon_TL,CORPORAL,BG21_US_ARMY_W_Recon,PRIVATE,BG21_US_ARMY_W_Recon,PRIVATE,BG21_US_ARMY_W_Recon,PRIVATE)
		GROUP9(BG21_US_ARMY_W_LightSupport,Light Support,BG21_US_ARMY_W,2,BG21_US_ARMY_W_SL,SERGEANT,BG21_US_ARMY_W_Radio,PRIVATE,BG21_US_ARMY_W_Medic,PRIVATE,BG21_US_ARMY_W_Grenadier,PRIVATE,BG21_US_ARMY_W_Rifleman,PRIVATE,BG21_US_ARMY_W_Rifleman,PRIVATE,BG21_US_ARMY_W_MG_TL,CORPORAL,BG21_US_ARMY_W_MG,PRIVATE,BG21_US_ARMY_W_MG_AS_TRIPOD,PRIVATE)
		GROUP9(BG21_US_ARMY_W_HeavySupport,Heavy Support,BG21_US_ARMY_W,2,BG21_US_ARMY_W_SL,SERGEANT,BG21_US_ARMY_W_Radio,PRIVATE,BG21_US_ARMY_W_Medic,PRIVATE,BG21_US_ARMY_W_Mortar_TL,CORPORAL,BG21_US_ARMY_W_Mortar,PRIVATE,BG21_US_ARMY_W_Mortar_AS,PRIVATE,BG21_US_ARMY_W_MG_TL,CORPORAL,BG21_US_ARMY_W_MG,PRIVATE,BG21_US_ARMY_W_MG_AS_TRIPOD,PRIVATE)
		GROUP8(BG21_US_ARMY_W_RifleSquad,Rifle Squad,BG21_US_ARMY_W,2,BG21_US_ARMY_W_SL,SERGEANT,BG21_US_ARMY_W_Radio,PRIVATE,BG21_US_ARMY_W_MG,PRIVATE,BG21_US_ARMY_W_MG_AS,PRIVATE,BG21_US_ARMY_W_Rifleman,PRIVATE,BG21_US_ARMY_W_Rifleman,PRIVATE,BG21_US_ARMY_W_Rifleman,PRIVATE,BG21_US_ARMY_W_TL,CORPORAL)
		GROUP7(BG21_US_ARMY_W_AssaultSquad,Assault Squad,BG21_US_ARMY_W,2,BG21_US_ARMY_W_SL,SERGEANT,BG21_US_ARMY_W_Radio,PRIVATE,BG21_US_ARMY_W_Engineer_Explos,PRIVATE,BG21_US_ARMY_W_Rifleman,PRIVATE,BG21_US_ARMY_W_BAR,PRIVATE,BG21_US_ARMY_W_BAR,PRIVATE,BG21_US_ARMY_W_TL,CORPORAL)
	};
};
class BG21_USAB101
{
	name = "[BG21] 101st Airborne";
	class Infantry
	{
		name = "1. Infantry";
		// 73rd D-Day anniversary
		GROUP2(BG21_USAB101_HQ2,HQ (2),BG21_USAB101,2,BG21_USAB101_PL,CAPTAIN,BG21_USAB101_PL2,LIEUTENANT)
		GROUP4(BG21_USAB101_Recon4,Recon (4),BG21_USAB101,2,BG21_USAB101_Recon_TL,CORPORAL,BG21_USAB101_Recon,PRIVATE,BG21_USAB101_Recon,PRIVATE,BG21_USAB101_Recon,PRIVATE)
		GROUP9(BG21_USAB101_LightSupport,Light Support,BG21_USAB101,2,BG21_USAB101_SL,SERGEANT,BG21_USAB101_Radio,PRIVATE,BG21_USAB101_Medic,PRIVATE,BG21_USAB101_Grenadier,PRIVATE,BG21_USAB101_Rifleman,PRIVATE,BG21_USAB101_Rifleman,PRIVATE,BG21_USAB101_MG_TL,CORPORAL,BG21_USAB101_MG,PRIVATE,BG21_USAB101_MG_AS_TRIPOD,PRIVATE)
		GROUP9(BG21_USAB101_HeavySupport,Heavy Support,BG21_USAB101,2,BG21_USAB101_SL,SERGEANT,BG21_USAB101_Radio,PRIVATE,BG21_USAB101_Medic,PRIVATE,BG21_USAB101_Mortar_TL,CORPORAL,BG21_USAB101_Mortar,PRIVATE,BG21_USAB101_Mortar_AS,PRIVATE,BG21_USAB101_MG_TL,CORPORAL,BG21_USAB101_MG,PRIVATE,BG21_USAB101_MG_AS_TRIPOD,PRIVATE)
		GROUP8(BG21_USAB101_RifleSquad,Rifle Squad,BG21_USAB101,2,BG21_USAB101_SL,SERGEANT,BG21_USAB101_Radio,PRIVATE,BG21_USAB101_MG,PRIVATE,BG21_USAB101_MG_AS,PRIVATE,BG21_USAB101_Rifleman,PRIVATE,BG21_USAB101_Rifleman,PRIVATE,BG21_USAB101_Rifleman,PRIVATE,BG21_USAB101_TL,CORPORAL)
		GROUP7(BG21_USAB101_AssaultSquad,Assault Squad,BG21_USAB101,2,BG21_USAB101_SL,SERGEANT,BG21_USAB101_Radio,PRIVATE,BG21_USAB101_Engineer_Explos,PRIVATE,BG21_USAB101_Rifleman,PRIVATE,BG21_USAB101_AssaultRifleman,PRIVATE,BG21_USAB101_AssaultRifleman,PRIVATE,BG21_USAB101_TL,CORPORAL)
	};
};
class BG21_US_DDAY
{
	name = "[BG21] US DDAY";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_US_DDAY_HQ,HQ Squad,BG21_US_DDAY,2,BG21_US_DDAY_PL,CAPTAIN,BG21_US_DDAY_Recon,PRIVATE,BG21_US_DDAY_Recon,PRIVATE)
		GROUP3(BG21_US_DDAY_RECON,Recon Squad,BG21_US_DDAY,2,BG21_US_DDAY_SL,SERGEANT,BG21_US_DDAY_Recon,PRIVATE,BG21_US_DDAY_Radio,PRIVATE)
		GROUP3(BG21_US_DDAY_ENGINEER1,Engineer Squad (Mines),BG21_US_DDAY,2,BG21_US_DDAY_Engineer_Mines,PRIVATE,BG21_US_DDAY_Engineer_Mines,PRIVATE,BG21_US_DDAY_Engineer_Mines,PRIVATE)
		GROUP3(BG21_US_DDAY_ENGINEER2,Engineer Squad (Explos),BG21_US_DDAY,2,BG21_US_DDAY_Engineer_Explos,PRIVATE,BG21_US_DDAY_Engineer_Explos,PRIVATE,BG21_US_DDAY_Engineer_Explos,PRIVATE)
		GROUP3(BG21_US_DDAY_ENGINEER3,Engineer Squad (Mixed),BG21_US_DDAY,2,BG21_US_DDAY_Engineer_Mines,PRIVATE,BG21_US_DDAY_Engineer_Mines,PRIVATE,BG21_US_DDAY_Engineer_Explos,PRIVATE)
		GROUP3(BG21_US_DDAY_AT,Anti-Tank Team,BG21_US_DDAY,2,BG21_US_DDAY_SL,CORPORAL,BG21_US_DDAY_AT,PRIVATE,BG21_US_DDAY_AT_AS,PRIVATE)
		GROUP3(BG21_US_DDAY_MORTAR,Mortar Team,BG21_US_DDAY,2,BG21_US_DDAY_Mortar_TL,CORPORAL,BG21_US_DDAY_Mortar,PRIVATE,BG21_US_DDAY_Mortar_AS,PRIVATE)
		GROUP7(BG21_US_DDAY_INF1,Infantry Squad,BG21_US_DDAY,2,BG21_US_DDAY_SL,SERGEANT,BG21_US_DDAY_TL,CORPORAL,BG21_US_DDAY_Rifleman,PRIVATE,BG21_US_DDAY_Rifleman,PRIVATE,BG21_US_DDAY_Radio,PRIVATE,BG21_US_DDAY_MG,PRIVATE,BG21_US_DDAY_MG_AS,PRIVATE)
	};
};
class BG21_USMC
{
	name = "[BG21] USMC";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_USMC_HQ,HQ Squad,BG21_USMC,2,BG21_USMC_PL,CAPTAIN,BG21_USMC_Recon,PRIVATE,BG21_USMC_Recon,PRIVATE)
		GROUP3(BG21_USMC_RECON,Recon Squad,BG21_USMC,2,BG21_USMC_SL,SERGEANT,BG21_USMC_Recon,PRIVATE,BG21_USMC_Radio,PRIVATE)
		GROUP3(BG21_USMC_ENGINEER1,Engineer Squad (Mines),BG21_USMC,2,BG21_USMC_Engineer_Mines,PRIVATE,BG21_USMC_Engineer_Mines,PRIVATE,BG21_USMC_Engineer_Mines,PRIVATE)
		GROUP3(BG21_USMC_ENGINEER2,Engineer Squad (Explos),BG21_USMC,2,BG21_USMC_Engineer_Explos,PRIVATE,BG21_USMC_Engineer_Explos,PRIVATE,BG21_USMC_Engineer_Explos,PRIVATE)
		GROUP3(BG21_USMC_ENGINEER3,Engineer Squad (Mixed),BG21_USMC,2,BG21_USMC_Engineer_Mines,PRIVATE,BG21_USMC_Engineer_Mines,PRIVATE,BG21_USMC_Engineer_Explos,PRIVATE)
		GROUP3(BG21_USMC_AT,Anti-Tank Team,BG21_USMC,2,BG21_USMC_SL,CORPORAL,BG21_USMC_AT,PRIVATE,BG21_USMC_AT_AS,PRIVATE)
		GROUP3(BG21_USMC_MORTAR,Mortar Team,BG21_USMC,2,BG21_USMC_Mortar_TL,CORPORAL,BG21_USMC_Mortar,PRIVATE,BG21_USMC_Mortar_AS,PRIVATE)
		GROUP7(BG21_USMC_INF1,Infantry Squad,BG21_USMC,2,BG21_USMC_SL,SERGEANT,BG21_USMC_TL,CORPORAL,BG21_USMC_Rifleman,PRIVATE,BG21_USMC_Rifleman,PRIVATE,BG21_USMC_Radio,PRIVATE,BG21_USMC_MG,PRIVATE,BG21_USMC_MG_AS,PRIVATE)
		// 73rd D-Day anniversary
		GROUP2(BG21_USMC_HQ2,HQ (2),BG21_USMC,2,BG21_USMC_PL,CAPTAIN,BG21_USMC_PL2,LIEUTENANT)
		GROUP4(BG21_USMC_Recon4,Recon (4),BG21_USMC,2,BG21_USMC_Recon_TL,CORPORAL,BG21_USMC_Recon,PRIVATE,BG21_USMC_Recon,PRIVATE,BG21_USMC_Recon,PRIVATE)
		GROUP9(BG21_USMC_LightSupport,Light Support,BG21_USMC,2,BG21_USMC_SL,SERGEANT,BG21_USMC_Radio,PRIVATE,BG21_USMC_Medic,PRIVATE,BG21_USMC_Grenadier,PRIVATE,BG21_USMC_Rifleman,PRIVATE,BG21_USMC_Rifleman,PRIVATE,BG21_USMC_MG_TL,CORPORAL,BG21_USMC_MG,PRIVATE,BG21_USMC_MG_AS_TRIPOD,PRIVATE)
		GROUP9(BG21_USMC_HeavySupport,Heavy Support,BG21_USMC,2,BG21_USMC_SL,SERGEANT,BG21_USMC_Radio,PRIVATE,BG21_USMC_Medic,PRIVATE,BG21_USMC_Mortar_TL,CORPORAL,BG21_USMC_Mortar,PRIVATE,BG21_USMC_Mortar_AS,PRIVATE,BG21_USMC_MG_TL,CORPORAL,BG21_USMC_MG,PRIVATE,BG21_USMC_MG_AS_TRIPOD,PRIVATE)
		GROUP8(BG21_USMC_RifleSquad,Rifle Squad,BG21_USMC,2,BG21_USMC_SL,SERGEANT,BG21_USMC_Radio,PRIVATE,BG21_USMC_MG,PRIVATE,BG21_USMC_MG_AS,PRIVATE,BG21_USMC_Rifleman,PRIVATE,BG21_USMC_Rifleman,PRIVATE,BG21_USMC_Rifleman,PRIVATE,BG21_USMC_TL,CORPORAL)
		GROUP7(BG21_USMC_AssaultSquad,Assault Squad,BG21_USMC,2,BG21_USMC_SL,SERGEANT,BG21_USMC_Radio,PRIVATE,BG21_USMC_Engineer_Explos,PRIVATE,BG21_USMC_Rifleman,PRIVATE,BG21_USMC_BAR,PRIVATE,BG21_USMC_BAR,PRIVATE,BG21_USMC_TL,CORPORAL)		
	};
};
