class BG21_US_ARMY
{
	name = "[BG21] US Army";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_US_ARMY_HQ,HQ Team,BG21_US_ARMY,1,Infantry,BG21_US_ARMY_PL,CAPTAIN,BG21_US_ARMY_Recon,PRIVATE,BG21_US_ARMY_Recon,PRIVATE)
		GROUP3(BG21_US_ARMY_RECON,Recon Team,BG21_US_ARMY,1,Infantry,BG21_US_ARMY_SL,SERGEANT,BG21_US_ARMY_Recon,PRIVATE,BG21_US_ARMY_Radio,PRIVATE)
		GROUP3(BG21_US_ARMY_ENGINEER1,Engineer Team (Mines),BG21_US_ARMY,1,Infantry,BG21_US_ARMY_Engineer_Mines,PRIVATE,BG21_US_ARMY_Engineer_Mines,PRIVATE,BG21_US_ARMY_Engineer_Mines,PRIVATE)
		GROUP3(BG21_US_ARMY_ENGINEER2,Engineer Team (Explos),BG21_US_ARMY,1,Infantry,BG21_US_ARMY_Engineer_Explos,PRIVATE,BG21_US_ARMY_Engineer_Explos,PRIVATE,BG21_US_ARMY_Engineer_Explos,PRIVATE)
		GROUP3(BG21_US_ARMY_ENGINEER3,Engineer Team (Mixed),BG21_US_ARMY,1,Infantry,BG21_US_ARMY_Engineer_Mines,PRIVATE,BG21_US_ARMY_Engineer_Mines,PRIVATE,BG21_US_ARMY_Engineer_Explos,PRIVATE)
		GROUP3(BG21_US_ARMY_AT,Engineer Team (Mixed),BG21_US_ARMY,1,Infantry,BG21_US_ARMY_SL,CORPORAL,BG21_US_ARMY_AT,PRIVATE,BG21_US_ARMY_AT_AS,PRIVATE)
		GROUP3(BG21_US_ARMY_MORTAR,Mortar Team,BG21_US_ARMY,1,Infantry,BG21_US_ARMY_SL,CORPORAL,BG21_US_ARMY_MORTAR,PRIVATE,BG21_US_ARMY_Radio,PRIVATE)
		GROUP7(BG21_US_ARMY_INF1,Infantry Squad,BG21_US_ARMY,1,Infantry,BG21_US_ARMY_SL,SERGEANT,BG21_US_ARMY_TL,CORPORAL,BG21_US_ARMY_Rifleman,PRIVATE,BG21_US_ARMY_Rifleman,PRIVATE,BG21_US_ARMY_Radio,PRIVATE,BG21_US_ARMY_MG,PRIVATE,BG21_US_ARMY_MG_AS,PRIVATE)
		};
};
class BG21_US_DDAY
{
	name = "[BG21] US DDAY";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_US_DDAY_HQ,HQ Squad,BG21_US_DDAY,1,Infantry,BG21_US_DDAY_PL,CAPTAIN,BG21_US_DDAY_Recon,PRIVATE,BG21_US_DDAY_Recon,PRIVATE)
		GROUP3(BG21_US_DDAY_RECON,Recon Squad,BG21_US_DDAY,1,Infantry,BG21_US_DDAY_SL,SERGEANT,BG21_US_DDAY_Recon,PRIVATE,BG21_US_DDAY_Radio,PRIVATE)
		GROUP3(BG21_US_DDAY_ENGINEER1,Engineer Squad (Mines),BG21_US_DDAY,1,Infantry,BG21_US_DDAY_Engineer_Mines,PRIVATE,BG21_US_DDAY_Engineer_Mines,PRIVATE,BG21_US_DDAY_Engineer_Mines,PRIVATE)
		GROUP3(BG21_US_DDAY_ENGINEER2,Engineer Squad (Explos),BG21_US_DDAY,1,Infantry,BG21_US_DDAY_Engineer_Explos,PRIVATE,BG21_US_DDAY_Engineer_Explos,PRIVATE,BG21_US_DDAY_Engineer_Explos,PRIVATE)
		GROUP3(BG21_US_DDAY_ENGINEER3,Engineer Squad (Mixed),BG21_US_DDAY,1,Infantry,BG21_US_DDAY_Engineer_Mines,PRIVATE,BG21_US_DDAY_Engineer_Mines,PRIVATE,BG21_US_DDAY_Engineer_Explos,PRIVATE)
		GROUP3(BG21_US_DDAY_AT,Engineer Squad (Mixed),BG21_US_DDAY,1,Infantry,BG21_US_DDAY_SL,CORPORAL,BG21_US_DDAY_AT,PRIVATE,BG21_US_DDAY_AT_AS,PRIVATE)
		GROUP3(BG21_US_DDAY_MORTAR,Mortar Team,BG21_US_DDAY,1,Infantry,BG21_US_DDAY_SL,CORPORAL,BG21_US_DDAY_MORTAR,PRIVATE,BG21_US_DDAY_Radio,PRIVATE)
		GROUP7(BG21_US_DDAY_INF1,Infantry Squad,BG21_US_DDAY,1,Infantry,BG21_US_DDAY_SL,SERGEANT,BG21_US_DDAY_TL,CORPORAL,BG21_US_DDAY_Rifleman,PRIVATE,BG21_US_DDAY_Rifleman,PRIVATE,BG21_US_DDAY_Radio,PRIVATE,BG21_US_DDAY_MG,PRIVATE,BG21_US_DDAY_MG_AS,PRIVATE)
	};
};
class BG21_USMC
{
	name = "[BG21] USMC";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_USMC_HQ,HQ Squad,BG21_USMC,1,Infantry,BG21_USMC_PL,CAPTAIN,BG21_USMC_Recon,PRIVATE,BG21_USMC_Recon,PRIVATE)
		GROUP3(BG21_USMC_RECON,Recon Squad,BG21_USMC,1,Infantry,BG21_USMC_SL,SERGEANT,BG21_USMC_Recon,PRIVATE,BG21_USMC_Radio,PRIVATE)
		GROUP3(BG21_USMC_ENGINEER1,Engineer Squad (Mines),BG21_USMC,1,Infantry,BG21_USMC_Engineer_Mines,PRIVATE,BG21_USMC_Engineer_Mines,PRIVATE,BG21_USMC_Engineer_Mines,PRIVATE)
		GROUP3(BG21_USMC_ENGINEER2,Engineer Squad (Explos),BG21_USMC,1,Infantry,BG21_USMC_Engineer_Explos,PRIVATE,BG21_USMC_Engineer_Explos,PRIVATE,BG21_USMC_Engineer_Explos,PRIVATE)
		GROUP3(BG21_USMC_ENGINEER3,Engineer Squad (Mixed),BG21_USMC,1,Infantry,BG21_USMC_Engineer_Mines,PRIVATE,BG21_USMC_Engineer_Mines,PRIVATE,BG21_USMC_Engineer_Explos,PRIVATE)
		GROUP3(BG21_USMC_AT,Engineer Squad (Mixed),BG21_USMC,1,Infantry,BG21_USMC_SL,CORPORAL,BG21_USMC_AT,PRIVATE,BG21_USMC_AT_AS,PRIVATE)
		GROUP3(BG21_USMC_MORTAR,Mortar Team,BG21_USMC,1,Infantry,BG21_USMC_SL,CORPORAL,BG21_USMC_MORTAR,PRIVATE,BG21_USMC_Radio,PRIVATE)
		GROUP7(BG21_USMC_INF1,Infantry Squad,BG21_USMC,1,Infantry,BG21_USMC_SL,SERGEANT,BG21_USMC_TL,CORPORAL,BG21_USMC_Rifleman,PRIVATE,BG21_USMC_Rifleman,PRIVATE,BG21_USMC_Radio,PRIVATE,BG21_USMC_MG,PRIVATE,BG21_USMC_MG_AS,PRIVATE)
	};
};
