class BG21_SOV_RA
{
	name = "[BG21] SOV (Spring)";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_SOV_RA_HQ,HQ Gruppa,BG21_SOV_RA,0,BG21_SOV_RA_PL,CAPTAIN,BG21_SOV_RA_Rifleman_MOSIN,PRIVATE,BG21_SOV_RA_Rifleman_MOSIN,PRIVATE)
		GROUP3(BG21_SOV_RA_RECON,Recon Gruppa,BG21_SOV_RA,0,BG21_SOV_RA_SL,SERGEANT,BG21_SOV_RA_Recon,PRIVATE,BG21_SOV_RA_Recon,PRIVATE)
		GROUP3(BG21_SOV_RA_PIONIER1,Pionier Gruppa (Mines),BG21_SOV_RA,0,BG21_SOV_RA_Pioneer_Mines,PRIVATE,BG21_SOV_RA_Pioneer_Mines,PRIVATE,BG21_SOV_RA_Pioneer_Mines,PRIVATE)
		GROUP3(BG21_SOV_RA_PIONIER2,Pionier Gruppa (Explos),BG21_SOV_RA,0,BG21_SOV_RA_Pioneer_Explos,PRIVATE,BG21_SOV_RA_Pioneer_Explos,PRIVATE,BG21_SOV_RA_Pioneer_Explos,PRIVATE)
		GROUP3(BG21_SOV_RA_PIONIER3,Pionier Gruppa (Mixed),BG21_SOV_RA,0,BG21_SOV_RA_Pioneer_Mines,PRIVATE,BG21_SOV_RA_Pioneer_Mines,PRIVATE,BG21_SOV_RA_Pioneer_Explos,PRIVATE)
		GROUP3(BG21_SOV_RA_AT,Ab. Gruppa,BG21_SOV_RA,0,BG21_SOV_RA_SL,CORPORAL,BG21_SOV_RA_AT,PRIVATE,BG21_SOV_RA_AT_AS,PRIVATE)
		GROUP3(BG21_SOV_RA_MORTAR,Mortar Team,BG21_SOV_RA,0,BG21_SOV_RA_Mortar_TL,CORPORAL,BG21_SOV_RA_MORTAR,PRIVATE,BG21_SOV_RA_Mortar_AS,PRIVATE)
		GROUP7(BG21_SOV_RA_INF1,Inf. Gruppa,BG21_SOV_RA,0,BG21_SOV_RA_SL,SERGEANT,BG21_SOV_RA_TL_SVT40,CORPORAL,BG21_SOV_RA_Rifleman_MOSIN,PRIVATE,BG21_SOV_RA_Rifleman_MOSIN,PRIVATE,BG21_SOV_RA_Radio,PRIVATE,BG21_SOV_RA_MG,PRIVATE,BG21_SOV_RA_MG_AS,PRIVATE)
	};
	class Armored 
	{
		name = "2. Tanks";
		GROUP3(BG21_SOV_RA_TankCrew1,Motorizovannyy Gruppa (3),BG21_SOV_RA,0,BG21_SOV_RA_Tank_Commander,LIEUTENANT,BG21_SOV_RA_Tank_Crew,SERGEANT,BG21_SOV_RA_Tank_Crew,PRIVATE)
		GROUP2(BG21_SOV_RA_TankCrew2,Motorizovannyy Gruppa (2),BG21_SOV_RA,0,BG21_SOV_RA_Tank_Commander,SERGEANT,BG21_SOV_RA_Tank_Crew,PRIVATE)		
	};
};
class BG21_SOV_RA_W
{
	name = "[BG21] SOV (Winter)";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_SOV_RA_W_HQ,HQ Gruppa,BG21_SOV_RA,0,BG21_SOV_RA_W_PL,CAPTAIN,BG21_SOV_RA_W_Rifleman_MOSIN,PRIVATE,BG21_SOV_RA_W_Rifleman_MOSIN,PRIVATE)
		GROUP3(BG21_SOV_RA_W_RECON,Recon Gruppa,BG21_SOV_RA,0,BG21_SOV_RA_W_SL,SERGEANT,BG21_SOV_RA_W_Recon,PRIVATE,BG21_SOV_RA_W_Recon,PRIVATE)
		GROUP3(BG21_SOV_RA_W_PIONIER1,Pionier Gruppa (Mines),BG21_SOV_RA,0,BG21_SOV_RA_W_Pioneer_Mines,PRIVATE,BG21_SOV_RA_W_Pioneer_Mines,PRIVATE,BG21_SOV_RA_W_Pioneer_Mines,PRIVATE)
		GROUP3(BG21_SOV_RA_W_PIONIER2,Pionier Gruppa (Explos),BG21_SOV_RA,0,BG21_SOV_RA_W_Pioneer_Explos,PRIVATE,BG21_SOV_RA_W_Pioneer_Explos,PRIVATE,BG21_SOV_RA_W_Pioneer_Explos,PRIVATE)
		GROUP3(BG21_SOV_RA_W_PIONIER3,Pionier Gruppa (Mixed),BG21_SOV_RA,0,BG21_SOV_RA_W_Pioneer_Mines,PRIVATE,BG21_SOV_RA_W_Pioneer_Mines,PRIVATE,BG21_SOV_RA_W_Pioneer_Explos,PRIVATE)
		GROUP3(BG21_SOV_RA_W_AT,Ab. Gruppa,BG21_SOV_RA,0,BG21_SOV_RA_W_SL,SERGEANT,BG21_SOV_RA_W_AT,PRIVATE,BG21_SOV_RA_W_AT_AS,PRIVATE)
		GROUP3(BG21_SOV_RA_W_MORTAR,Mortar Team,BG21_SOV_RA,0,BG21_SOV_RA_W_Mortar_TL,CORPORAL,BG21_SOV_RA_W_MORTAR,PRIVATE,BG21_SOV_RA_W_Mortar_AS,PRIVATE)
		GROUP7(BG21_SOV_RA_W_INF1,Inf. Gruppa,BG21_SOV_RA,0,BG21_SOV_RA_W_SL,SERGEANT,BG21_SOV_RA_W_TL_SVT40,CORPORAL,BG21_SOV_RA_W_Rifleman_MOSIN,PRIVATE,BG21_SOV_RA_W_Rifleman_MOSIN,PRIVATE,BG21_SOV_RA_W_Radio,PRIVATE,BG21_SOV_RA_W_MG,PRIVATE,BG21_SOV_RA_W_MG_AS,PRIVATE)
	};
};
