class BG21_UK_ARMY
{
	name = "[BG21] UK Army";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_UK_ARMY_HQ,HQ Squad,BG21_UK_ARMY,2,BG21_UK_ARMY_PL,CAPTAIN,BG21_UK_ARMY_Recon,PRIVATE,BG21_UK_ARMY_Recon,PRIVATE)
		GROUP3(BG21_UK_ARMY_RECON,Recon Squad,BG21_UK_ARMY,2,BG21_UK_ARMY_SL,SERGEANT,BG21_UK_ARMY_Recon,PRIVATE,BG21_UK_ARMY_Radio,PRIVATE)
		GROUP3(BG21_UK_ARMY_ENGINEER1,Engineer Squad (Mines),BG21_UK_ARMY,2,BG21_UK_ARMY_Engineer_Mines,PRIVATE,BG21_UK_ARMY_Engineer_Mines,PRIVATE,BG21_UK_ARMY_Engineer_Mines,PRIVATE)
		GROUP3(BG21_UK_ARMY_ENGINEER2,Engineer Squad (Explos),BG21_UK_ARMY,2,BG21_UK_ARMY_Engineer_Explos,PRIVATE,BG21_UK_ARMY_Engineer_Explos,PRIVATE,BG21_UK_ARMY_Engineer_Explos,PRIVATE)
		GROUP3(BG21_UK_ARMY_ENGINEER3,Engineer Squad (Mixed),BG21_UK_ARMY,2,BG21_UK_ARMY_Engineer_Mines,PRIVATE,BG21_UK_ARMY_Engineer_Mines,PRIVATE,BG21_UK_ARMY_Engineer_Explos,PRIVATE)
		GROUP3(BG21_UK_ARMY_AT,AT Squad,BG21_UK_ARMY,2,BG21_UK_ARMY_SL,SERGEANT,BG21_UK_ARMY_AT,PRIVATE,BG21_UK_ARMY_AT_AS,PRIVATE)
		GROUP3(BG21_UK_ARMY_MORTAR,Mortar Team,BG21_UK_ARMY,2,BG21_UK_ARMY_Mortar_TL,CORPORAL,BG21_UK_ARMY_Mortar,PRIVATE,BG21_UK_ARMY_Mortar_AS,PRIVATE)
		GROUP7(BG21_UK_ARMY_INF1,Infantry Squad,BG21_UK_ARMY,2,BG21_UK_ARMY_SL,SERGEANT,BG21_UK_ARMY_TL,CORPORAL,BG21_UK_ARMY_Rifleman,PRIVATE,BG21_UK_ARMY_Rifleman,PRIVATE,BG21_UK_ARMY_Radio,PRIVATE,BG21_UK_ARMY_MG,PRIVATE,BG21_UK_ARMY_MG_AS,PRIVATE)
		// 73rd D-Day Anniversary
		GROUP2(BG21_UK_ARMY_HQ2,HQ (2),BG21_UK_ARMY,2,BG21_UK_ARMY_PL,CAPTAIN,BG21_UK_ARMY_PL2,LIEUTENANT)
		GROUP4(BG21_UK_ARMY_Recon4,Recon (4),BG21_UK_ARMY,2,BG21_UK_ARMY_Recon_TL,CORPORAL,BG21_UK_ARMY_Radio,PRIVATE,BG21_UK_ARMY_Recon,PRIVATE,BG21_UK_ARMY_Recon,PRIVATE)
		GROUP9(BG21_UK_ARMY_LightSupport,Light Support,BG21_UK_ARMY,2,BG21_UK_ARMY_SL,SERGEANT,BG21_UK_ARMY_Radio,PRIVATE,BG21_UK_ARMY_Medic,PRIVATE,BG21_UK_ARMY_Grenadier,PRIVATE,BG21_UK_ARMY_Rifleman,PRIVATE,BG21_UK_ARMY_Rifleman,PRIVATE,BG21_UK_ARMY_MG_TL,CORPORAL,BG21_UK_ARMY_MG,PRIVATE,BG21_UK_ARMY_MG_AS,PRIVATE)
		GROUP9(BG21_UK_ARMY_HeavySupport,Heavy Support,BG21_UK_ARMY,2,BG21_UK_ARMY_SL,SERGEANT,BG21_UK_ARMY_Radio,PRIVATE,BG21_UK_ARMY_Medic,PRIVATE,BG21_UK_ARMY_Mortar_TL,CORPORAL,BG21_UK_ARMY_Mortar,PRIVATE,BG21_UK_ARMY_Mortar_AS,PRIVATE,BG21_UK_ARMY_MG_TL,CORPORAL,BG21_UK_ARMY_MG,PRIVATE,BG21_UK_ARMY_MG_AS,PRIVATE)
		GROUP8(BG21_UK_ARMY_RifleSquad,Rifle Squad,BG21_UK_ARMY,2,BG21_UK_ARMY_SL,SERGEANT,BG21_UK_ARMY_Radio,PRIVATE,BG21_UK_ARMY_BREN,PRIVATE,BG21_UK_ARMY_BREN_AS,PRIVATE,BG21_UK_ARMY_Rifleman,PRIVATE,BG21_UK_ARMY_Rifleman,PRIVATE,BG21_UK_ARMY_Rifleman,PRIVATE,BG21_UK_ARMY_TL,CORPORAL)
		GROUP7(BG21_UK_ARMY_AssaultSquad,Assault Squad,BG21_UK_ARMY,2,BG21_UK_ARMY_SL,SERGEANT,BG21_UK_ARMY_Radio,PRIVATE,BG21_UK_ARMY_Engineer_Explos,PRIVATE,BG21_UK_ARMY_Rifleman,PRIVATE,BG21_UK_ARMY_Rifleman_Sten,PRIVATE,BG21_UK_ARMY_BREN,PRIVATE,BG21_UK_ARMY_TL,CORPORAL)
		// Tanks
		GROUP3(BG21_UK_ARMY_TankCrew1,Tank crew (3),BG21_UK_ARMY,1,BG21_UK_Army_Tank_Commander,LIEUTENANT,BG21_UK_Army_Tank_Crew,SERGEANT,BG21_UK_Army_Tank_Crew,PRIVATE)
		GROUP2(BG21_UK_ARMY_TankCrew2,Tank crew (2),BG21_UK_ARMY,1,BG21_UK_Army_Tank_Commander,SERGEANT,BG21_UK_Army_Tank_Crew,PRIVATE)
	};
};
class BG21_UK_DR
{
	name = "[BG21] UK Desert Rats";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_UK_DR_HQ,HQ Squad,BG21_UK_ARMY,2,BG21_UK_DR_PL,CAPTAIN,BG21_UK_DR_Recon,PRIVATE,BG21_UK_DR_Recon,PRIVATE)
		GROUP3(BG21_UK_DR_RECON,Recon Squad,BG21_UK_ARMY,2,BG21_UK_DR_SL,SERGEANT,BG21_UK_DR_Recon,PRIVATE,BG21_UK_DR_Radio,PRIVATE)
		GROUP3(BG21_UK_DR_ENGINEER1,Engineer Squad (Mines),BG21_UK_ARMY,2,BG21_UK_DR_Engineer_Mines,PRIVATE,BG21_UK_DR_Engineer_Mines,PRIVATE,BG21_UK_DR_Engineer_Mines,PRIVATE)
		GROUP3(BG21_UK_DR_ENGINEER2,Engineer Squad (Explos),BG21_UK_ARMY,2,BG21_UK_DR_Engineer_Explos,PRIVATE,BG21_UK_DR_Engineer_Explos,PRIVATE,BG21_UK_DR_Engineer_Explos,PRIVATE)
		GROUP3(BG21_UK_DR_ENGINEER3,Engineer Squad (Mixed),BG21_UK_ARMY,2,BG21_UK_DR_Engineer_Mines,PRIVATE,BG21_UK_DR_Engineer_Mines,PRIVATE,BG21_UK_DR_Engineer_Explos,PRIVATE)
		GROUP3(BG21_UK_DR_AT,AT Squad,BG21_UK_ARMY,2,BG21_UK_DR_SL,SERGEANT,BG21_UK_DR_AT,PRIVATE,BG21_UK_DR_AT_AS,PRIVATE)
		GROUP3(BG21_UK_DR_MORTAR,Mortar Team,BG21_UK_ARMY,2,BG21_UK_DR_Mortar_TL,CORPORAL,BG21_UK_DR_Mortar,PRIVATE,BG21_UK_DR_Mortar_AS,PRIVATE)
		GROUP7(BG21_UK_DR_INF1,Infantry Squad,BG21_UK_ARMY,2,BG21_UK_DR_SL,SERGEANT,BG21_UK_DR_TL,CORPORAL,BG21_UK_DR_Rifleman,PRIVATE,BG21_UK_DR_Rifleman,PRIVATE,BG21_UK_DR_Radio,PRIVATE,BG21_UK_DR_MG,PRIVATE,BG21_UK_DR_MG_AS,PRIVATE)
		// 73rd D-Day Anniversary
		GROUP2(BG21_UK_DR_HQ2,HQ (2),BG21_UK_ARMY,2,BG21_UK_DR_PL,CAPTAIN,BG21_UK_DR_PL2,LIEUTENANT)
		GROUP4(BG21_UK_DR_Recon4,Recon (4),BG21_UK_ARMY,2,BG21_UK_DR_Recon_TL,CORPORAL,BG21_UK_DR_Radio,PRIVATE,BG21_UK_DR_Recon,PRIVATE,BG21_UK_DR_Recon,PRIVATE)
		GROUP9(BG21_UK_DR_LightSupport,Light Support,BG21_UK_ARMY,2,BG21_UK_DR_SL,SERGEANT,BG21_UK_DR_Radio,PRIVATE,BG21_UK_DR_Medic,PRIVATE,BG21_UK_DR_Grenadier,PRIVATE,BG21_UK_DR_Rifleman,PRIVATE,BG21_UK_DR_Rifleman,PRIVATE,BG21_UK_DR_MG_TL,CORPORAL,BG21_UK_DR_MG,PRIVATE,BG21_UK_DR_MG_AS,PRIVATE)
		GROUP9(BG21_UK_DR_HeavySupport,Heavy Support,BG21_UK_ARMY,2,BG21_UK_DR_SL,SERGEANT,BG21_UK_DR_Radio,PRIVATE,BG21_UK_DR_Medic,PRIVATE,BG21_UK_DR_Mortar_TL,CORPORAL,BG21_UK_DR_Mortar,PRIVATE,BG21_UK_DR_Mortar_AS,PRIVATE,BG21_UK_DR_MG_TL,CORPORAL,BG21_UK_DR_MG,PRIVATE,BG21_UK_DR_MG_AS,PRIVATE)
		GROUP8(BG21_UK_DR_RifleSquad,Rifle Squad,BG21_UK_ARMY,2,BG21_UK_DR_SL,SERGEANT,BG21_UK_DR_Radio,PRIVATE,BG21_UK_DR_BREN,PRIVATE,BG21_UK_DR_BREN_AS,PRIVATE,BG21_UK_DR_Rifleman,PRIVATE,BG21_UK_DR_Rifleman,PRIVATE,BG21_UK_DR_Rifleman,PRIVATE,BG21_UK_DR_TL,CORPORAL)
		GROUP7(BG21_UK_DR_AssaultSquad,Assault Squad,BG21_UK_ARMY,2,BG21_UK_DR_SL,SERGEANT,BG21_UK_DR_Radio,PRIVATE,BG21_UK_DR_Engineer_Explos,PRIVATE,BG21_UK_DR_Rifleman,PRIVATE,BG21_UK_DR_Rifleman_Sten,PRIVATE,BG21_UK_DR_BREN,PRIVATE,BG21_UK_DR_TL,CORPORAL)
	};
};
class BG21_UK_AB
{
	name = "[BG21] UK Airborne";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_UK_AB_HQ,HQ Squad,BG21_UK_ARMY,2,BG21_UK_AB_PL,CAPTAIN,BG21_UK_AB_Recon,PRIVATE,BG21_UK_AB_Recon,PRIVATE)
		GROUP3(BG21_UK_AB_RECON,Recon Squad,BG21_UK_ARMY,2,BG21_UK_AB_SL,SERGEANT,BG21_UK_AB_Recon,PRIVATE,BG21_UK_AB_Radio,PRIVATE)
		GROUP3(BG21_UK_AB_ENGINEER1,Engineer Squad (Mines),BG21_UK_ARMY,2,BG21_UK_AB_Engineer_Mines,PRIVATE,BG21_UK_AB_Engineer_Mines,PRIVATE,BG21_UK_AB_Engineer_Mines,PRIVATE)
		GROUP3(BG21_UK_AB_ENGINEER2,Engineer Squad (Explos),BG21_UK_ARMY,2,BG21_UK_AB_Engineer_Explos,PRIVATE,BG21_UK_AB_Engineer_Explos,PRIVATE,BG21_UK_AB_Engineer_Explos,PRIVATE)
		GROUP3(BG21_UK_AB_ENGINEER3,Engineer Squad (Mixed),BG21_UK_ARMY,2,BG21_UK_AB_Engineer_Mines,PRIVATE,BG21_UK_AB_Engineer_Mines,PRIVATE,BG21_UK_AB_Engineer_Explos,PRIVATE)
		GROUP3(BG21_UK_AB_AT,AT Squad,BG21_UK_ARMY,2,BG21_UK_AB_SL,SERGEANT,BG21_UK_AB_AT,PRIVATE,BG21_UK_AB_AT_AS,PRIVATE)
		GROUP3(BG21_UK_AB_MORTAR,Mortar Team,BG21_UK_ARMY,2,BG21_UK_AB_Mortar_TL,CORPORAL,BG21_UK_AB_Mortar,PRIVATE,BG21_UK_AB_Mortar_AS,PRIVATE)
		GROUP7(BG21_UK_AB_INF1,Infantry Squad,BG21_UK_ARMY,2,BG21_UK_AB_SL,SERGEANT,BG21_UK_AB_TL,CORPORAL,BG21_UK_AB_Rifleman,PRIVATE,BG21_UK_AB_Rifleman,PRIVATE,BG21_UK_AB_Radio,PRIVATE,BG21_UK_AB_MG,PRIVATE,BG21_UK_AB_MG_AS,PRIVATE)
		// 73rd D-Day Anniversary
		GROUP2(BG21_UK_AB_HQ2,HQ (2),BG21_UK_AB,2,BG21_UK_AB_PL,CAPTAIN,BG21_UK_AB_PL2,LIEUTENANT)
		GROUP4(BG21_UK_AB_Recon4,Recon (4),BG21_UK_AB,2,BG21_UK_AB_Recon_TL,CORPORAL,BG21_UK_AB_Radio,PRIVATE,BG21_UK_AB_Recon,PRIVATE,BG21_UK_AB_Recon,PRIVATE)
		GROUP9(BG21_UK_AB_LightSupport,Light Support,BG21_UK_AB,2,BG21_UK_AB_SL,SERGEANT,BG21_UK_AB_Radio,PRIVATE,BG21_UK_AB_Medic,PRIVATE,BG21_UK_AB_Grenadier,PRIVATE,BG21_UK_AB_Rifleman,PRIVATE,BG21_UK_AB_Rifleman,PRIVATE,BG21_UK_AB_MG_TL,CORPORAL,BG21_UK_AB_MG,PRIVATE,BG21_UK_AB_MG_AS,PRIVATE)
		GROUP9(BG21_UK_AB_HeavySupport,Heavy Support,BG21_UK_AB,2,BG21_UK_AB_SL,SERGEANT,BG21_UK_AB_Radio,PRIVATE,BG21_UK_AB_Medic,PRIVATE,BG21_UK_AB_Mortar_TL,CORPORAL,BG21_UK_AB_Mortar,PRIVATE,BG21_UK_AB_Mortar_AS,PRIVATE,BG21_UK_AB_MG_TL,CORPORAL,BG21_UK_AB_MG,PRIVATE,BG21_UK_AB_MG_AS,PRIVATE)
		GROUP8(BG21_UK_AB_RifleSquad,Rifle Squad,BG21_UK_AB,2,BG21_UK_AB_SL,SERGEANT,BG21_UK_AB_Radio,PRIVATE,BG21_UK_AB_BREN,PRIVATE,BG21_UK_AB_BREN_AS,PRIVATE,BG21_UK_AB_Rifleman,PRIVATE,BG21_UK_AB_Rifleman,PRIVATE,BG21_UK_AB_Rifleman,PRIVATE,BG21_UK_AB_TL,CORPORAL)
		GROUP7(BG21_UK_AB_AssaultSquad,Assault Squad,BG21_UK_AB,2,BG21_UK_AB_SL,SERGEANT,BG21_UK_AB_Radio,PRIVATE,BG21_UK_AB_Engineer_Explos,PRIVATE,BG21_UK_AB_Rifleman,PRIVATE,BG21_UK_AB_Rifleman_Sten,PRIVATE,BG21_UK_AB_BREN,PRIVATE,BG21_UK_AB_TL,CORPORAL)
	};
};
class BG21_UK_CDO
{
	name = "[BG21] UK Commandos";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_UK_CDO_HQ,HQ Squad,BG21_UK_ARMY,2,BG21_UK_CDO_PL,CAPTAIN,BG21_UK_CDO_Recon,PRIVATE,BG21_UK_CDO_Recon,PRIVATE)
		GROUP3(BG21_UK_CDO_RECON,Recon Squad,BG21_UK_ARMY,2,BG21_UK_CDO_SL,SERGEANT,BG21_UK_CDO_Recon,PRIVATE,BG21_UK_CDO_Radio,PRIVATE)
		GROUP3(BG21_UK_CDO_ENGINEER1,Engineer Squad (Mines),BG21_UK_ARMY,2,BG21_UK_CDO_Engineer_Mines,PRIVATE,BG21_UK_CDO_Engineer_Mines,PRIVATE,BG21_UK_CDO_Engineer_Mines,PRIVATE)
		GROUP3(BG21_UK_CDO_ENGINEER2,Engineer Squad (Explos),BG21_UK_ARMY,2,BG21_UK_CDO_Engineer_Explos,PRIVATE,BG21_UK_CDO_Engineer_Explos,PRIVATE,BG21_UK_CDO_Engineer_Explos,PRIVATE)
		GROUP3(BG21_UK_CDO_ENGINEER3,Engineer Squad (Mixed),BG21_UK_ARMY,2,BG21_UK_CDO_Engineer_Mines,PRIVATE,BG21_UK_CDO_Engineer_Mines,PRIVATE,BG21_UK_CDO_Engineer_Explos,PRIVATE)
		GROUP3(BG21_UK_CDO_AT,AT Squad,BG21_UK_ARMY,2,BG21_UK_CDO_SL,SERGEANT,BG21_UK_CDO_AT,PRIVATE,BG21_UK_CDO_AT_AS,PRIVATE)
		GROUP3(BG21_UK_CDO_MORTAR,Mortar Team,BG21_UK_ARMY,2,BG21_UK_CDO_Mortar_TL,CORPORAL,BG21_UK_CDO_MORTAR,PRIVATE,BG21_UK_CDO_Mortar_AS,PRIVATE)
		GROUP7(BG21_UK_CDO_INF1,Infantry Squad,BG21_UK_ARMY,2,BG21_UK_CDO_SL,SERGEANT,BG21_UK_CDO_TL,CORPORAL,BG21_UK_CDO_Rifleman,PRIVATE,BG21_UK_CDO_Rifleman,PRIVATE,BG21_UK_CDO_Radio,PRIVATE,BG21_UK_CDO_MG,PRIVATE,BG21_UK_CDO_MG_AS,PRIVATE)
		// 73rd D-Day Anniversary
		GROUP2(BG21_UK_CDO_HQ2,HQ (2),BG21_UK_CDO,2,BG21_UK_CDO_PL,CAPTAIN,BG21_UK_CDO_PL2,LIEUTENANT)
		GROUP4(BG21_UK_CDO_Recon4,Recon (4),BG21_UK_CDO,2,BG21_UK_CDO_Recon_TL,CORPORAL,BG21_UK_CDO_Radio,PRIVATE,BG21_UK_CDO_Recon,PRIVATE,BG21_UK_CDO_Recon,PRIVATE)
		GROUP9(BG21_UK_CDO_LightSupport,Light Support,BG21_UK_CDO,2,BG21_UK_CDO_SL,SERGEANT,BG21_UK_CDO_Radio,PRIVATE,BG21_UK_CDO_Medic,PRIVATE,BG21_UK_CDO_Grenadier,PRIVATE,BG21_UK_CDO_Rifleman,PRIVATE,BG21_UK_CDO_Rifleman,PRIVATE,BG21_UK_CDO_MG_TL,CORPORAL,BG21_UK_CDO_MG,PRIVATE,BG21_UK_CDO_MG_AS,PRIVATE)
		GROUP9(BG21_UK_CDO_HeavySupport,Heavy Support,BG21_UK_CDO,2,BG21_UK_CDO_SL,SERGEANT,BG21_UK_CDO_Radio,PRIVATE,BG21_UK_CDO_Medic,PRIVATE,BG21_UK_CDO_Mortar_TL,CORPORAL,BG21_UK_CDO_Mortar,PRIVATE,BG21_UK_CDO_Mortar_AS,PRIVATE,BG21_UK_CDO_MG_TL,CORPORAL,BG21_UK_CDO_MG,PRIVATE,BG21_UK_CDO_MG_AS,PRIVATE)
		GROUP8(BG21_UK_CDO_RifleSquad,Rifle Squad,BG21_UK_CDO,2,BG21_UK_CDO_SL,SERGEANT,BG21_UK_CDO_Radio,PRIVATE,BG21_UK_CDO_BREN,PRIVATE,BG21_UK_CDO_BREN_AS,PRIVATE,BG21_UK_CDO_Rifleman,PRIVATE,BG21_UK_CDO_Rifleman,PRIVATE,BG21_UK_CDO_Rifleman,PRIVATE,BG21_UK_CDO_TL,CORPORAL)
		GROUP7(BG21_UK_CDO_AssaultSquad,Assault Squad,BG21_UK_CDO,2,BG21_UK_CDO_SL,SERGEANT,BG21_UK_CDO_Radio,PRIVATE,BG21_UK_CDO_Engineer_Explos,PRIVATE,BG21_UK_CDO_Rifleman,PRIVATE,BG21_UK_CDO_Rifleman_Sten,PRIVATE,BG21_UK_CDO_BREN,PRIVATE,BG21_UK_CDO_TL,CORPORAL)
	};
};
