class BG21_UK_ARMY
{
	name = "[BG21] UK Army";
	class Infantry
	{
		name = "1. Infantry";
		GROUP3(BG21_UK_ARMY_HQ,HQ Squad,BG21_UK_ARMY,1,Infantry,BG21_UK_ARMY_PL,CAPTAIN,BG21_UK_ARMY_Recon,PRIVATE,BG21_UK_ARMY_Recon,PRIVATE)
		GROUP3(BG21_UK_ARMY_RECON,Recon Squad,BG21_UK_ARMY,1,Infantry,BG21_UK_ARMY_SL,SERGEANT,BG21_UK_ARMY_Recon,PRIVATE,BG21_UK_ARMY_Radio,PRIVATE)
		GROUP3(BG21_UK_ARMY_ENGINEER1,Engineer Squad (Mines),BG21_UK_ARMY,1,Infantry,BG21_UK_ARMY_Engineer_Mines,PRIVATE,BG21_UK_ARMY_Engineer_Mines,PRIVATE,BG21_UK_ARMY_Engineer_Mines,PRIVATE)
		GROUP3(BG21_UK_ARMY_ENGINEER2,Engineer Squad (Explos),BG21_UK_ARMY,1,Infantry,BG21_UK_ARMY_Engineer_Explos,PRIVATE,BG21_UK_ARMY_Engineer_Explos,PRIVATE,BG21_UK_ARMY_Engineer_Explos,PRIVATE)
		GROUP3(BG21_UK_ARMY_ENGINEER3,Engineer Squad (Mixed),BG21_UK_ARMY,1,Infantry,BG21_UK_ARMY_Engineer_Mines,PRIVATE,BG21_UK_ARMY_Engineer_Mines,PRIVATE,BG21_UK_ARMY_Engineer_Explos,PRIVATE)
		GROUP3(BG21_UK_ARMY_AT,AT Squad,BG21_UK_ARMY,1,Infantry,BG21_UK_ARMY_SL,SERGEANT,BG21_UK_ARMY_AT,PRIVATE,BG21_UK_ARMY_AT_AS,PRIVATE)
		GROUP3(BG21_UK_ARMY_MORTAR,Mortar Team,BG21_UK_ARMY,1,Infantry,BG21_UK_ARMY_SL,CORPORAL,BG21_UK_ARMY_MORTAR,PRIVATE,BG21_UK_ARMY_Radio,PRIVATE)
		GROUP7(BG21_UK_ARMY_INF1,Infantry Squad,BG21_UK_ARMY,1,Infantry,BG21_UK_ARMY_SL,SERGEANT,BG21_UK_ARMY_TL,CORPORAL,BG21_UK_ARMY_Rifleman,PRIVATE,BG21_UK_ARMY_Rifleman,PRIVATE,BG21_UK_ARMY_Radio,PRIVATE,BG21_UK_ARMY_MG,PRIVATE,BG21_UK_ARMY_MG_AS,PRIVATE)
	};
};
